# 1、基础镜像
FROM centos:7

# 2、镜像作者和电子邮箱
MAINTAINER chenlong "chenlong220192@gmail.com"

# 3、在构建镜像时，指定镜像的工作目录。之后的命令都是基于此工作目录，不存在则自动创建。
WORKDIR /temp

# 4、切换yum源
RUN sed -e 's|^mirrorlist=|#mirrorlist=|g' \
        -e 's|^#baseurl=http://mirror.centos.org|baseurl=https://mirrors.tuna.tsinghua.edu.cn|g' \
        -i.bak \
        /etc/yum.repos.d/CentOS-*.repo

# 5、安装常用工具
RUN yum clean all && \
    yum makecache -y && \
    yum install -y \
    net-tools \
    telnet \
    iproute \
    curl \
    wget && \
    yum clean all

# 6、安装jdk
RUN wget http://nginx-downloads.internal:9011/jdk-8u202-linux-x64.tar.gz && \
    mkdir -p /usr/local/jdk && \
    mv jdk-8u202-linux-x64.tar.gz /usr/local/jdk && \
    cd /usr/local/jdk && \
    tar -xf jdk-8u202-linux-x64.tar.gz && \
    rm -rf jdk-8u202-linux-x64.tar.gz

# 7、变量环境
ENV JAVA_HOME=/usr/local/jdk/jdk1.8.0_202
ENV CLASSPATH=$JAVA_HOME/bin
ENV PATH=.:$JAVA_HOME/bin:$PATH

# 8、容器启动后执行命令
CMD ["java","-version"]

# 构建命令
#### docker build -f Dockerfile-jdk-centos7 --rm -t base/jdk:8u202-centos7 .
#### docker tag base/jdk:8u202-centos7 nexus.internal:8082/local/base/jdk:8u202-centos7
#### docker rmi -f base/jdk:8u202-centos7
#### docker push nexus.internal:8082/local/base/jdk:8u202-centos7
