# 1、基础镜像
FROM centos:7

# 2、镜像作者和电子邮箱
MAINTAINER chenlong "chenlong220192@gmail.com"

# 3、在构建镜像时，指定镜像的工作目录。之后的命令都是基于此工作目录，不存在则自动创建。
# WORKDIR /temp

# 4、安装wget
RUN yum install -y wget

# 5、切换yum源
RUN sed -e 's|^mirrorlist=|#mirrorlist=|g' \
        -e 's|^#baseurl=http://mirror.centos.org|baseurl=https://mirrors.tuna.tsinghua.edu.cn|g' \
        -i.bak \
        /etc/yum.repos.d/CentOS-*.repo

# 6、安装常用工具
RUN yum clean all && \
    yum makecache -y && \
    yum install -y \
    net-tools \
    telnet \
    iproute \
    curl \
    wget && \
    yum clean all

# 7、安装jre
RUN wget http://nginx-downloads.internal:9011/server-jre-8u202-linux-x64.tar.gz && \
    mkdir -p /usr/local/jre && \
    mv server-jre-8u202-linux-x64.tar.gz /usr/local/jre && \
    cd /usr/local/jre && \
    tar -xf server-jre-8u202-linux-x64.tar.gz && \
    rm -rf server-jre-8u202-linux-x64.tar.gz

# 8、变量环境
ENV JAVA_HOME=/usr/local/jre/jdk1.8.0_202
ENV CLASSPATH=$JAVA_HOME/bin
ENV PATH=.:$JAVA_HOME/bin:$PATH

# 9、容器启动后执行命令
CMD ["java","-version"]

# 构建命令
#### docker build -f Dockerfile-server-jre-centos7 --rm -t base/server-jre:8u202-centos7 .
#### docker tag base/server-jre:8u202-centos7 nexus.internal:8082/local/base/server-jre:8u202-centos7
#### docker rmi -f base/server-jre:8u202-centos7
#### docker push nexus.internal:8082/local/base/server-jre:8u202-centos7
